### ISSUE TITLE
Adding Cypress Configuration

### ISSUE THREAD

**Issue by DevPres** [jm2097/angular-boilerplate#645]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a ready to use cypress test configuration

**Describe alternatives you've considered**
Playwright

**Additional context**
E2E tests are very useful in a front-end environment. I believe that inserting a Cypress configuration that is ready to use can improve this boilerplate (which I'm loving). I would like to try setting up Cypress for the project.

**Comment by juanmesa2097** [comment]
@DevPres thank you. I like Cypress but I think Playwright has superior capabilities and its development is more innovative and active compared to Cypress. It would definitely be nice to have it integrated into this project and ready to use. Would you be interested in submitting a PR to set up Playwright?

**Comment by DevPres** [comment]
Hello @juanmesa2097 ,

I have never used Playwright before, but I am definitely willing to give it a try!

**Comment by juanmesa2097** [comment]
Hey @DevPres, sounds awesome. Thanks a lot!

**Comment by DevPres** [comment]
Hi @juanmesa2097 !

've been reading about Playwright and Angular, and I've learned that component testing is not officially supported by Playwright. While there's an option to use a third-party package to address this, such as [this repo](https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular), it appears to only work with [versatile-angular](https://marmicode.io/blog/versatile-angular).

Considering the current situation, I believe it might be better to hold off on implementing this and instead consider using Cypress, which fully supports Angular component testing. Please let me know your thoughts on this!

**Comment by juanmesa2097** [comment]
Hey @DevPres, I agree with your perspective. I see there's an issue already opened for this on the Playwright repo. Since the project isn't using [analog](https://github.com/analogjs/analog) and doesn't fulfill all the specified constraints in [versatile-angular](https://marmicode.io/blog/versatile-angular), and to the best of my knowledge, Angular still isn't fully compatible with [VIte](https://vitejs.dev/). With that in mind, I believe it makes sense to go with Cypress for now. We can then decide later on whether migrating to Playwright would be a worthwhile move, especially once it can be seamlessly integrated.

**Comment by DevPres** [comment]
Hi @juanmesa2097  Sorry for the late response, but I was on vacation XD

I'm glad to hear that you understand the perspective. In the upcoming days, I'll be working on implementing Cypress, and when Playwright fully supports Angular in the future, I'll be happy to implement it in this repository.

**Comment by juanmesa2097** [comment]
@DevPres sounds excellent, thank you! 😀

**Comment by DevPres** [comment]
Hi @jm2097 ,
I apologize for my long absence, luckly I found a job shortly after my last message, I haven't been very skilled at time management XD.
Now, things have stabilized, and I can dedicate some time to the OSS.
So, I'm here to tell you that I'm starting to work on it again these days.

**Comment by jm2097** [comment]
Hey @DevPres, congratulations on your new job! I appreciate you taking the time to notify me. It all sounds good to me. 🙂

**Comment by DevPres** [comment]
Thank @jm2097 !! i Appreciate it!

i just dropped the PR! let me know what you think about! Slowly, but i can improve it with your suggestion!
#648

**Comment by jm2097** [comment]
@DevPres thanks a lot for your contribution. I just left two remarks on your PR. 👍
